/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static Util.Criptografia.criptografar;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Usuarios;

/**
 *
 * @author jonas
 */
public class AlterarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AlterarUsuario
     */
    Usuarios usuario;
    List <Usuarios> list = new ArrayList<Usuarios>();
    public AlterarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarUsuario = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridBusca = new javax.swing.JTable();
        btCancelar1 = new javax.swing.JButton();
        Selecionar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        cbGerencia = new javax.swing.JCheckBox();

        BuscarUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        BuscarUsuario.setMinimumSize(new java.awt.Dimension(640, 307));
        BuscarUsuario.setUndecorated(true);
        BuscarUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gridBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Acesso Gerencial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridBusca);

        BuscarUsuario.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 340, 147));

        btCancelar1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar1.setText("Fechar");
        btCancelar1.setBorderPainted(false);
        btCancelar1.setContentAreaFilled(false);
        btCancelar1.setFocusPainted(false);
        btCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar1ActionPerformed(evt);
            }
        });
        BuscarUsuario.getContentPane().add(btCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, 40));

        Selecionar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Selecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        Selecionar.setText("Selecionar");
        Selecionar.setBorderPainted(false);
        Selecionar.setContentAreaFilled(false);
        Selecionar.setFocusPainted(false);
        Selecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });
        BuscarUsuario.getContentPane().add(Selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 116, 40));

        lbTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Pesquisar Usuario");
        BuscarUsuario.getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 50));

        btBuscar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setBorderPainted(false);
        btBuscar.setContentAreaFilled(false);
        btBuscar.setFocusPainted(false);
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        BuscarUsuario.getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(452, 186));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Alterar Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 11, -1, 40));

        txtLogin.setEditable(false);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 127, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nova Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, -1));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 127, -1));

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar.setText(" Cancelar");
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        btCancelar.setContentAreaFilled(false);
        btCancelar.setFocusPainted(false);
        btCancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 30));

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btSalvar.setText(" Efetivar");
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, 30));

        cbGerencia.setText("Privilegio administrativo");
        cbGerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGerenciaActionPerformed(evt);
            }
        });
        getContentPane().add(cbGerencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 40));

        setSize(new java.awt.Dimension(452, 186));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try{
            String pass=String.valueOf(txtSenha.getPassword());
            String login=txtLogin.getText();
            if(pass.length()<4){
                JOptionPane.showMessageDialog(null, "A senha deve conter no minimo 4 digitos !");
            }else if(login.isEmpty()){
                JOptionPane.showMessageDialog(null, "Selecione o usuario que deseja alterar");
            }else{
                
                String senha = criptografar(new String(txtSenha.getPassword()));
                String ckGerencia = cbGerencia.isSelected()==false ? "F" : "T";
                Usuarios usuario = new Usuarios(login,senha,ckGerencia);
                usuario.alterar(usuario);
                this.dispose();
            }
        }catch(Exception e){

            e.printStackTrace();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void gridBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridBuscaMouseClicked
        try{
            if(evt.getClickCount() == 2){
                String user= String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(),0));
                String txtGerencia=String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(),1));
                txtLogin.setText(user);
                if(txtGerencia=="SIM"){
                cbGerencia.setSelected(true);
                }else{
                cbGerencia.setSelected(false);
                }
                BuscarUsuario.setVisible(false);                
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Selecione o usuario que deseja Alterar");
        }
    }//GEN-LAST:event_gridBuscaMouseClicked

    private void btCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar1ActionPerformed
        BuscarUsuario.setVisible(false);
    }//GEN-LAST:event_btCancelar1ActionPerformed

    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed
        try{
            String user= String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(),0));
            String txtGerencia=String.valueOf(gridBusca.getValueAt(gridBusca.getSelectedRow(),1));
            txtLogin.setText(user);
            if(txtGerencia=="SIM"){
                cbGerencia.setSelected(true);
            }else{
                cbGerencia.setSelected(false);
            }              
            BuscarUsuario.setVisible(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Selecione o usuario que deseja Alterar");
        }
    }//GEN-LAST:event_SelecionarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) gridBusca.getModel();
        modelo.setNumRows(0);
        TableColumnModel modeltable2 = gridBusca.getColumnModel();
        modeltable2.getColumn(0).setPreferredWidth(45);
        centralizar(gridBusca,0);
        centralizar(gridBusca,1);
        Usuarios usuario = new Usuarios("","","");
        usuario.selectAlteraUser();
        list=usuario.getListUsers();
        try {
            String lenlist;
            List<Usuarios> listagem = list;
            lenlist=String.valueOf(listagem.size());
            for (Usuarios user : listagem) {
                String gerencia= user.getGerencia();
                if(gerencia.equals("T")){
                    gerencia="SIM";
                }else {
                    gerencia="NAO";
                }
                
                modelo.addRow(new Object[]{user.getUsuario(),gerencia});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao buscar os usuarios, contate o suporte técnico");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarUsuario.setLocationRelativeTo(null);
        BuscarUsuario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbGerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGerenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGerenciaActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        /// TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed
    
    private static void centralizar(JTable table, int column) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setCellRenderer(centerRenderer);       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BuscarUsuario;
    private javax.swing.JButton Selecionar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbGerencia;
    private javax.swing.JTable gridBusca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
