/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static Util.Criptografia.criptografar;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *
 * @author jonas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    boolean status=false;
    
    public TelaPrincipal() {
        initComponents();
        bloquearAcesso();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        btLogar = new javax.swing.JToggleButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 235, 235));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerenciador de Usuarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 270, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/userInicial.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 260, 200));

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoInicial.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 370, 230));

        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, -1));

        btSair.setBackground(new java.awt.Color(235, 235, 235));
        btSair.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.setToolTipText("");
        btSair.setBorderPainted(false);
        btSair.setContentAreaFilled(false);
        btSair.setFocusPainted(false);
        btSair.setMaximumSize(new java.awt.Dimension(230, 50));
        btSair.setMinimumSize(new java.awt.Dimension(120, 45));
        btSair.setPreferredSize(new java.awt.Dimension(180, 45));
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSairMouseExited(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 370, 50));

        lbLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLogin.setText("Login:");
        getContentPane().add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 272, 60, 20));

        lbSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSenha.setText("Senha:");
        getContentPane().add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 322, 60, 20));

        btLogar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btLogar.setText("Entrar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 100, -1));

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 140, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 430));

        btIncluir.setBackground(new java.awt.Color(235, 235, 235));
        btIncluir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btIncluir.setText("Incluir Usuario");
        btIncluir.setToolTipText("");
        btIncluir.setBorderPainted(false);
        btIncluir.setContentAreaFilled(false);
        btIncluir.setFocusPainted(false);
        btIncluir.setMaximumSize(new java.awt.Dimension(230, 50));
        btIncluir.setMinimumSize(new java.awt.Dimension(120, 45));
        btIncluir.setPreferredSize(new java.awt.Dimension(180, 45));
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btIncluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btIncluirMouseExited(evt);
            }
        });
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 370, 50));

        btAlterar.setBackground(new java.awt.Color(235, 235, 235));
        btAlterar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btAlterar.setText("Alterar Usuario");
        btAlterar.setToolTipText("");
        btAlterar.setBorderPainted(false);
        btAlterar.setContentAreaFilled(false);
        btAlterar.setFocusPainted(false);
        btAlterar.setMaximumSize(new java.awt.Dimension(230, 50));
        btAlterar.setMinimumSize(new java.awt.Dimension(120, 45));
        btAlterar.setPreferredSize(new java.awt.Dimension(180, 45));
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAlterarMouseExited(evt);
            }
        });
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 370, 50));

        btExcluir.setBackground(new java.awt.Color(235, 235, 235));
        btExcluir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btExcluir.setText("Excluir Usuario");
        btExcluir.setToolTipText("");
        btExcluir.setBorderPainted(false);
        btExcluir.setContentAreaFilled(false);
        btExcluir.setFocusPainted(false);
        btExcluir.setMaximumSize(new java.awt.Dimension(230, 50));
        btExcluir.setMinimumSize(new java.awt.Dimension(120, 45));
        btExcluir.setPreferredSize(new java.awt.Dimension(180, 45));
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExcluirMouseExited(evt);
            }
        });
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 370, 50));

        lbFundo.setBackground(new java.awt.Color(235, 235, 235));
        lbFundo.setOpaque(true);
        getContentPane().add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -6, 640, 440));

        setSize(new java.awt.Dimension(640, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        try{
            String login = txtLogin.getText();
            String senha= new String(txtSenha.getPassword());
            //System.out.println("login:"+login+"senha:"+senha);

            if(status==true){
                txtLogin.setText("");
                txtSenha.setText("");
                btLogar.setText("Entrar");
                bloquearAcesso();
                status=false;

            }else if(status==false){
                String senhaCrip = (criptografar(senha));
                Usuarios usuario = new Usuarios(login);
                String senhaBanco=usuario.selectall(usuario).getSenha();
                String gerencia = usuario.selectall(usuario).getGerencia();
                if (senhaBanco.equals(senhaCrip)==true){
                    if(gerencia.equals("T")){
                        btLogar.setText("Sair");
                        btLogar.setSelected(true);
                        liberarAcesso();
                        status=true;
                    }
                    else{
                        bloquearAcesso();
                        JOptionPane.showMessageDialog(null, "Usuario não possui permissão de acesso !");
                    }
                }
                else{
                    btLogar.setSelected(false);
                    JOptionPane.showMessageDialog(null, "Senha incorreta !");
                    status=false;
                }
            }
        }catch(Exception e){
            btLogar.setSelected(false);
            JOptionPane.showMessageDialog(null, "Erro ao se conectar com as credenciais fornecidas ! \n Verifique e tente acessar novamente !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btLogarActionPerformed

    private void btSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseEntered
        setButton(btSair);
    }//GEN-LAST:event_btSairMouseEntered

    private void btSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseExited
        resetButton(btSair);
    }//GEN-LAST:event_btSairMouseExited

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btIncluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMouseEntered
        setButton(btIncluir);
    }//GEN-LAST:event_btIncluirMouseEntered

    private void btIncluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMouseExited
        resetButton(btIncluir);
    }//GEN-LAST:event_btIncluirMouseExited

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        IncluirUsuario tela = new IncluirUsuario();
        tela.setVisible(status);
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseEntered
        setButton(btAlterar);
    }//GEN-LAST:event_btAlterarMouseEntered

    private void btAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseExited
        resetButton(btAlterar);
    }//GEN-LAST:event_btAlterarMouseExited

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        AlterarUsuario tela = new AlterarUsuario();
        tela.setVisible(status);
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseEntered
        setButton(btExcluir);
    }//GEN-LAST:event_btExcluirMouseEntered

    private void btExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseExited
        resetButton(btExcluir);
    }//GEN-LAST:event_btExcluirMouseExited

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        ExcluirUsuario tela = new ExcluirUsuario();
        tela.setVisible(status);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            btLogar.doClick();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        String minuscula= txtLogin.getText();
        txtLogin.setText(minuscula.toUpperCase());
    }//GEN-LAST:event_txtLoginFocusLost

    private static void setButton(JButton botao){
        botao.setBackground(new Color(200,200,200));
        botao.setFont(new Font("Trebuchet MS",1,19));
    }
    
    private static void resetButton(JButton botao){
        botao.setBackground(new Color(235,235,235));
        botao.setFont(new Font("Trebuchet MS",1,18));
    }
    
    private void bloquearAcesso(){
        txtLogin.setEnabled(true);
        txtSenha.setEnabled(true);
        btIncluir.setEnabled(false);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        btLogar.setSelected(false);
        txtLogin.requestFocus(true);
    }
    
    private void liberarAcesso(){
        txtLogin.setEnabled(false);
        txtSenha.setEnabled(false);
        btIncluir.setEnabled(true);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JToggleButton btLogar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
